apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "copilot-metric-viewer.fullname" . }}
  labels:
    {{- include "copilot-metric-viewer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "copilot-metric-viewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "copilot-metric-viewer.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "copilot-metric-viewer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: VUE_APP_MOCKED_DATA
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: VUE_APP_MOCKED_DATA
            - name: VUE_APP_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: VUE_APP_SCOPE
            - name: VUE_APP_GITHUB_ORG
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: VUE_APP_GITHUB_ORG
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: GITHUB_CLIENT_SECRET
            - name: SESSION_SECRET
              valueFrom: # SEE LENNAA
                configMapKeyRef:
                  name: app-env
                  key: SESSION_SECRET
            - name: VUE_APP_GITHUB_API
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: VUE_APP_GITHUB_API
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
